### ISSUE TITLE
Twilio

### ISSUE THREAD

**Issue by Ajayrahulapiswi** [DevipriyaSarkar/Damsel-In-Distress#1]
is twilio a free api..
and how to get the twilio api

**Comment by DevipriyaSarkar** [comment]
Twilio provides some features and limited number of messages for free.
Sign up [here](https://www.twilio.com/try-twilio) and get your Twilio API credentials.
Please read up in the documentations as well about how to use Twilio APIs and features.

**Comment by Ajayrahulapiswi** [comment]
Can u show me how the API key looks like?
And where did you get the distance matrix api key?
